export const fallbackPayload = {
  product: {
    name: "Clash for Mac",
    version: "0.2.0",
    parity_source: "Clash for Windows 0.20.39 macOS arm64 public release artifact",
  },
  pages: [
    { id: "general", title: "General", summary: "Overview, runtime status, mode, system proxy and TUN toggles." },
    { id: "proxies", title: "Proxies", summary: "Proxy groups, selections, delay indicators and quick switching." },
    { id: "profiles", title: "Profiles", summary: "Subscription import, update, validation and profile lifecycle." },
    { id: "providers", title: "Providers", summary: "Proxy providers, rule providers, health checks and update actions." },
    { id: "logs", title: "Logs", summary: "Core logs, helper logs and filtered runtime diagnostics." },
    { id: "connections", title: "Connections", summary: "Live connection list, close-all action and traffic visibility." },
    { id: "rules", title: "Rules", summary: "Rule matching visibility and router/provider diagnostics." },
    { id: "settings", title: "Settings", summary: "Shell settings, startup, deep link, helper and migration options." },
    { id: "feedback", title: "Feedback", summary: "About, feedback and migration references from the original app." },
  ],
  settings: {
    launch_at_login: false,
    random_controller_port: true,
    retain_window_bounds: true,
    show_tray_proxy_delay_indicator: true,
    check_for_updates: false,
    only_arm64_macos_supported: true,
  },
  platform: {
    minimum_macos: "13.0",
    intel_supported: false,
    system_proxy_strategy: "objc2 SystemConfiguration SCPreferences with networksetup fallback",
    helper_strategy: "SMAppService privileged helper (Login Items approval required)",
    launchd_strategy: "typed launchd contract, no ad-hoc shell scripts in product logic",
    tun_strategy: "SmAppServiceRootHelper",
  },
  quality: {
    performance: {
      multiplier_vs_cfw_02039: 3,
      cold_start_p95_ms: 700,
      page_switch_p95_ms: 16,
      proxy_toggle_p95_ms: 150,
      profile_apply_p95_ms: 450,
      max_idle_rss_mb: 90,
      log_ingest_events_per_sec: 10000,
    },
    stability: {
      crash_free_session_rate_basis_points: 9995,
      restore_system_proxy_on_exit: true,
      rollback_failed_profile_apply: true,
      idempotent_helper_install: true,
      tun_failure_restores_previous_route: true,
      single_instance_deep_link_safe: true,
    },
    parity_gates: [],
  },
};

export const fallbackSettingsSnapshot = {
  persisted: false,
  paths: {
    app_home: "~/Library/Application Support/Clash for Mac",
    settings_file: "~/Library/Application Support/Clash for Mac/cfw-settings.yaml",
    config_file: "~/Library/Application Support/Clash for Mac/config.yaml",
    profiles_dir: "~/Library/Application Support/Clash for Mac/profiles",
    logs_dir: "~/Library/Application Support/Clash for Mac/logs",
    cores_dir: "~/Library/Application Support/Clash for Mac/cores",
    helpers_dir: "~/Library/Application Support/Clash for Mac/helpers",
  },
  settings: {
    schema_version: 1,
    runtime_mode: "Rule",
    active_profile: null,
    system_proxy: false,
    proxy_bypass: [],
    tun_mode: false,
    mixin: false,
    mixin_yaml: "",
    profile_parser_script: "",
    tray_script: "",
    child_process_command: "",
    allow_lan: false,
    enable_ipv6: false,
    launch_at_login: false,
    silent_start: false,
    break_connections_on_proxy_change: true,
    theme: "light",
    font_family: "",
    "interface-name": "",
    mixed_port: 7890,
    external_controller_host: "127.0.0.1",
    external_controller_port: 9090,
    secret: null,
    retain_window_bounds: true,
    show_tray_proxy_delay_indicator: true,
    usePacScript: false,
    pacScript: "",
    randomMixedPort: false,
    delayTestUrl: "http://www.gstatic.com/generate_204",
    only_arm64_macos_supported: true,
  },
};

export const fallbackCoreStatus = {
  state: "MissingBinary",
  pid: null,
  message: "Missing ~/Library/Application Support/Clash for Mac/cores/clash-darwin",
  spec: {
    binary_path: "~/Library/Application Support/Clash for Mac/cores/clash-darwin",
    config_path: "~/Library/Application Support/Clash for Mac/config.yaml",
    home_dir: "~/Library/Application Support/Clash for Mac",
    log_file: "~/Library/Application Support/Clash for Mac/logs/clash-core.log",
    controller_host: "127.0.0.1",
    controller_port: 9090,
    mixed_port: 7890,
  },
};

export const state = {
  payload: fallbackPayload,
  settingsSnapshot: fallbackSettingsSnapshot,
  coreStatus: fallbackCoreStatus,
  networkDiagnostics: null,
  activePage: "general",
  mode: "Rule",
  logLevel: "info",
  proxyFilter: "",
  activeProxyGroup: null,
  collapsedProxyGroups: new Set(),
  logFilter: "all",
  logSearch: "",
  logsPaused: false,
  connectionSearch: "",
  ruleSearch: "",
  mixinYaml: "",
  pacScript: "",
  profileParserScript: "",
  trayScript: "",
  childProcessCommand: "",
  connectionSort: "age",
  connectionSortDesc: false,
  connectionPaused: false,
  connectionDetailId: null,
  closingConnectionIds: new Set(),
  closingAllConnections: false,
  deepLinks: [],
  lastRefresh: "Just now",
  controllerStatus: "reference preview only",
  toggles: {
    systemProxy: false,
    tunMode: false,
    mixin: false,
    allowLan: false,
    startAtLogin: false,
    breakOnProxyChange: true,
    silentStart: false,
    testingDelays: false,
    hideUnavailable: false,
    enableIpv6: false,
    proxyDelayIndicator: true,
    showProxyFilter: true,
    showProxiesList: true,
    usePacScript: false,
    showProcess: true,
  },
  proxyBlinkNode: null,
  traffic: {
    upload: 0,
    download: 0,
    runtimeSeconds: 0,
    memoryMb: 0,
  },
  // Wall-clock millis when the core was last observed Running; null when stopped.
  // Drives a real uptime instead of a fabricated, always-incrementing counter.
  coreStartedAt: null,
  // Real SMAppService registration state (service_mode_status command).
  serviceModeStatus: null,
  // Live GeoIP DB status from app home (geoip.metadb / Country.mmdb).
  geoipStatus: null,
  geoipUpdating: false,
  controllerVersion: null,
  connectionStream: {
    at: 0,
    uploadTotal: 0,
    downloadTotal: 0,
    rows: new Map(),
  },
  profiles: [],
  profileInspector: null,
  /** @type {{ id: string, x: number, y: number } | null} */
  profileContextMenu: null,
  /** @type {{ kind: string, id?: string, payload?: any } | null} */
  glassDialog: null,
  proxyGroups: [],
  logs: [],
  connections: [],
  providers: [],
  ruleProviders: [],
  rules: [],
  providerActions: new Set(),
  providerBulkActions: new Set(),
};

export const navInitials = {
  general: "G",
  proxies: "P",
  profiles: "F",
  providers: "V",
  logs: "L",
  connections: "C",
  rules: "R",
  settings: "S",
  feedback: "?",
};

export const primaryNavIds = new Set(["general", "proxies", "profiles", "providers", "logs", "connections", "rules", "settings", "feedback"]);
export const MAX_LOG_ROWS = 200;
export const MAX_CONNECTION_ROWS = 500;
export const runtime = {
  renderFrame: null,
  connectionsPatchFrame: null,
  globalEventsBound: false,
  connectionRowEls: null,
};

