package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"path/filepath"
	"testing"
	"time"
)

func TestX963PrivateKeyRoundTripShape(t *testing.T) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	encoded := x963PrivateKey(key)
	if len(encoded) != 97 || encoded[0] != 4 {
		t.Fatalf("unexpected X9.63 private key shape: len=%d prefix=%d", len(encoded), encoded[0])
	}
}

func TestGenerateRefusesOverwrite(t *testing.T) {
	directory := t.TempDir()
	previous, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(directory); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(previous); err != nil {
			t.Errorf("restore working directory: %v", err)
		}
	})
	now := time.Unix(1_777_777_777, 0).UTC()
	if err := generate(now); err != nil {
		t.Fatalf("first generation failed: %v", err)
	}
	for _, name := range []string{certificateName, privateKeyName, manifestName} {
		info, err := os.Stat(filepath.Join(directory, name))
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode().Perm() != 0o600 || info.Size() == 0 {
			t.Fatalf("unsafe output %s: mode=%o size=%d", name, info.Mode().Perm(), info.Size())
		}
	}
	if err := generate(now); err == nil {
		t.Fatal("second generation unexpectedly replaced existing identity")
	}

	certificateDER, err := os.ReadFile(filepath.Join(directory, certificateName))
	if err != nil {
		t.Fatal(err)
	}
	certificate, err := x509.ParseCertificate(certificateDER)
	if err != nil {
		t.Fatalf("parse certificate: %v", err)
	}
	if certificate.Subject.CommonName != serverName || len(certificate.DNSNames) != 1 || certificate.DNSNames[0] != serverName {
		t.Fatalf("certificate name differs: subject=%q DNS=%v", certificate.Subject.CommonName, certificate.DNSNames)
	}
	if certificate.IsCA || certificate.NotAfter.Sub(certificate.NotBefore) > maximumLifetime+30*time.Second {
		t.Fatalf("certificate policy differs: is_ca=%v lifetime=%v", certificate.IsCA, certificate.NotAfter.Sub(certificate.NotBefore))
	}

	privateBytes, err := os.ReadFile(filepath.Join(directory, privateKeyName))
	if err != nil {
		t.Fatal(err)
	}
	if len(privateBytes) != 97 || privateBytes[0] != 4 {
		t.Fatalf("private key encoding differs: len=%d", len(privateBytes))
	}
	d := new(big.Int).SetBytes(privateBytes[65:])
	x, y := elliptic.P256().ScalarBaseMult(d.Bytes())
	publicKey, ok := certificate.PublicKey.(*ecdsa.PublicKey)
	if !ok || x.Cmp(publicKey.X) != 0 || y.Cmp(publicKey.Y) != 0 {
		t.Fatal("certificate and X9.63 private key do not match")
	}

	manifestBytes, err := os.ReadFile(filepath.Join(directory, manifestName))
	if err != nil {
		t.Fatal(err)
	}
	var receipt manifest
	if err := json.Unmarshal(manifestBytes, &receipt); err != nil {
		t.Fatalf("decode manifest: %v", err)
	}
	certificateDigest := sha256.Sum256(certificateDER)
	privateKeyDigest := sha256.Sum256(privateBytes)
	if receipt.CertificateSHA256 != hex.EncodeToString(certificateDigest[:]) || receipt.PrivateKeySHA256 != hex.EncodeToString(privateKeyDigest[:]) {
		t.Fatal("identity manifest digests do not bind generated bytes")
	}
}
